name: user_live_location
description: user_live_location offers you how to get the geographic location of a user or device on a Google map.
version: 0.0.3
homepage: https://github.com/Anonymousgaurav

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^1.0.0
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.0.9
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/2.0x/location_pin.png
    - assets/images/3.0x/location_pin.png
    - assets/images/location_pin.png
    - assets/images/2.0x/user_pin.png
    - assets/images/3.0x/user_pin.png
    - assets/images/user_pin.png

